#Aqui vamos a copiar lo que pone en el proyecto de Biblioteca
#Este nombre lo elegimos nosotros(veterinaria_db)
#Aqui pondremos la configuracion su usamos MySql

spring.application.name=veterinaria-backend
#Este es el que copiamos para poner en el navegador
spring.datasource.url=jdbc:h2:mem:veterinaria_db
#Esto lo suele detectar solo al ver que lo tiene en las dependencias
spring.datasource.driver-class-name=org.h2.Driver
#Para que no tengas que crear las tablas cen la base de datos con SQP.
spring.jpa.hibernate.ddl-auto=create-drop
#Este nos ayuda a entender si esta funcionando todo, Te dice las sentencias SQL que se han ejecutado.
spring.jpa.show-sql=true
#Si queremos que salga h2 en el navegador debemos activarlo porque por defecto no lo hace.
spring.h2.console.enabled=true

